version: '3.8'

services:
  spark-master:
    image: mi-spark-py39
    container_name: spark-master
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master && tail -f /dev/null"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - cluster-net
    shm_size: '6gb'
    deploy:
      resources:
        limits:
          cpus: '1'

  spark-worker-1:
    image: mi-spark-py39
    container_name: spark-worker-1
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master
    networks:
      - cluster-net
    shm_size: '6gb'
    deploy:
      resources:
        limits:
          cpus: '1'

  ray-head:
    image: rayproject/ray:latest
    container_name: ray-head
    command: >
      bash -c "ray start --head --port=6379 --dashboard-host 0.0.0.0 --dashboard-port=8265 --ray-client-server-port=10001 --disable-usage-stats && tail -f /dev/null"
    ports:
      - "8265:8265"
      - "6379:6379"
      - "10001:10001"
    networks:
      - cluster-net
    shm_size: '6gb'
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '1'

  ray-worker-1:
    image: rayproject/ray:latest
    container_name: ray-worker-1
    command: >
      bash -c "ray start --address=ray-head:6379 --disable-usage-stats && tail -f /dev/null"
    depends_on:
      - ray-head
    networks:
      - cluster-net
    shm_size: '6gb'
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '1'

networks:
  cluster-net:
    driver: bridge
