version: '3.8'

services:
  # ===========================
  #       SPARK SERVICES
  # ===========================
  spark-master:
    image: mi-spark-py39
    container_name: spark-master
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./benchmarks:/benchmarks
      - ./EDA:/EDA
      - ./pipelines:/pipelines
      - ./logs:/logs
      - ./configs:/configs
    shm_size: '2gb'
  
  spark-worker-1:
    image: mi-spark-py39
    container_name: spark-worker-1
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    depends_on:
      - spark-master
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./benchmarks:/benchmarks
      - ./EDA:/EDA
      - ./pipelines:/pipelines
      - ./logs:/logs
      - ./configs:/configs
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8g

  spark-worker-2:
    image: mi-spark-py39
    container_name: spark-worker-2
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    depends_on:
      - spark-master
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./benchmarks:/benchmarks
      - ./EDA:/EDA
      - ./pipelines:/pipelines
      - ./logs:/logs
      - ./configs:/configs

    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8g

  # ===========================
  #         RAY SERVICES
  # ===========================
  ray-head:
    image: rayproject/ray:latest
    container_name: ray-head
    command: >
      bash -c "ray start --head --port=6379 --dashboard-host 0.0.0.0 --dashboard-port 8265 --ray-client-server-port=10001 --disable-usage-stats && tail -f /dev/null"
    ports:
      - "8265:8265"
      - "6379:6379"
      - "10001:10001"
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./benchmarks:/benchmarks
      - ./EDA:/EDA
      - ./pipelines:/pipelines
      - ./logs:/logs
      - ./configs:/configs
    shm_size: '2gb'
    tty: true
    stdin_open: true
  ray-worker-1:
    image: rayproject/ray:latest
    container_name: ray-worker-1
    command: >
      bash -c "ray start --address=ray-head:6379 --disable-usage-stats && tail -f /dev/null"
    depends_on:
      - ray-head
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./benchmarks:/benchmarks
      - ./EDA:/EDA
      - ./pipelines:/pipelines
      - ./logs:/logs
      - ./configs:/configs
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8g

  ray-worker-2:
    image: rayproject/ray:latest
    container_name: ray-worker-2
    command: >
      bash -c "ray start --address=ray-head:6379 --disable-usage-stats && tail -f /dev/null"
    depends_on:
      - ray-head
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./benchmarks:/benchmarks
      - ./EDA:/EDA
      - ./pipelines:/pipelines
      - ./logs:/logs
      - ./configs:/configs
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8g
